export const categories = [
  {
    title: 'SNACKS & DRINKS',
    data: [
      {
        id: '1',
        name: 'Munchies',
        image: require('./assets/bru.jpg'),
        description: 'Classic salted potato chips Classic',
        price: 24,
        quantity: '200g',
      },
      {
        id: '2',
        name: 'Sweets',
        image: require('./assets/jamun.jpg'),
        description: 'Fuel your day with our whole Fuel your day with our whole',
        price: 20,
        quantity: '100g',
      },
      {
        id: '3',
        name: 'Biscuits',
        image: require('./assets/biscuit.jpg'),
        description: 'Get a taste of comfort with our',
        price: 24,
        quantity: '150g',
      },
      {
        id: '4',
        name: 'Cold Drinks',
        image: require('./assets/cocaloca.jpeg'),
        description: 'Snack smarter with our low-calorie',
        price: 24,
        quantity: '200g',
      },
      {
        id: '5',
        name: 'Noodles, Pasta, Vermi',
        image: require('./assets/maggi.jpg'),
        description: 'Experience a crunchy twist',
        price: 24,
        quantity: '900g',
      },
      {
        id: '6',
        name: 'Breakfast & Sauces',
        image: require('./assets/corn.jpg'),
        description: 'Classic salted potato chips',
        price: 24,
        quantity: '20g',
      },
      {
        id: '7',
        name: 'Tea, Coffee & more',
        image: require('./assets/bru.jpg'),
        description: 'Discover a perfect blend of sweet',
        price: 200,
        quantity: '200g',
      },
      {
        id: '8',
        name: 'Dairy, Bread & Eggs',
        image: require('./assets/amul.jpg'),
        description: 'Indulge in the ultimate sweet',
        price: 24,
        quantity: '170g',
      },
    ],
  },
  {
    title: 'BEAUTY & PERSONAL CARE',
    data: [
      {
        id: '9',
        name: 'Hair Care',
        image: require('./assets/shampoo.jpg'),
        description: 'Classic salted potato chips',
        price: 24,
        quantity: '200g',
      },
      {
        id: '10',
        name: 'Cleaning Essentials',
        image: require('./assets/vim.jpg'),
        description: 'Indulge in the ultimate sweet',
        price: 24,
        quantity: '200g',
      },
      {
        id: '11',
        name: 'Battery & Power',
        image: require('./assets/battery.jpg'),
        description: 'Experience a crunchy twist',
        price: 24,
        quantity: '200g',
      },
      {
        id: '12',
        name: 'Bottles',
        image: require('./assets/bottle.jpg'),
        description: 'Classic salted potato chips',
        price: 24,
        quantity: '200g',
      },
      {
        id: '13',
        name: 'Snack',
        image: require('./assets/biscuit.jpg'),
        description: 'Snack smarter with our low-calorie',
        price: 24,
        quantity: '200g',
      },
      {
        id: '14',
        name: 'Kitchen Essentials',
        image: require('./assets/everest.jpg'),
        description: 'Discover a perfect blend of sweet',
        price: 24,
        quantity: '200g',
      },
      {
        id: '15',
        name: 'Bottles',
        image: require('./assets/bottle.jpg'),
        description: 'Classic salted potato chips',
        price: 24,
        quantity: '200g',
      },
    ],
  },
];

export const subCategories = [
  {
    id: '1',
    name: 'Chips',
    image: require('./assets/cheez.jpeg'),
    categoryId: '1',
    price: 24,
    quantity: '200g',
    description: 'Classic salted potato chips',
  },
  {
    id: '2',
    name: 'Cookies',
    image: require('./assets/biscuit.jpg'),
    categoryId: '1',
    price: 299,
    quantity: '500g',
    description: 'Satisfy your crunch cravings',
  },
  {
    id: '3',
    name: 'Juices',
    image: require('./assets/thumbsup.jpeg'),
    categoryId: '2',
    price: 201,
    quantity: '700g',
    description: 'Indulge in the ultimate.',
  },
  {
    id: '4',
    name: 'Soda',
    image: require('./assets/bru.jpg'),
    categoryId: '2',
    price: 29,
    quantity: '100g',
    description: 'Classic salted potato chips',
  },
  {
    id: '1',
    name: 'Chips',
    image: require('./assets/cheez.jpeg'),
    categoryId: '3',
    price: 24,
    quantity: '200g',
    description: 'Classic salted potato chips',
  },
  {
    id: '2',
    name: 'Cookies',
    image: require('./assets/biscuit.jpg'),
    categoryId: '3',
    price: 299,
    quantity: '500g',
    description: 'Satisfy your crunch cravings',
  },
  {
    id: '3',
    name: 'Juices',
    image: require('./assets/thumbsup.jpeg'),
    categoryId: '4',
    price: 201,
    quantity: '700g',
    description: 'Indulge in the ultimate.',
  },
  {
    id: '4',
    name: 'Soda',
    image: require('./assets/bru.jpg'),
    categoryId: '4',
    price: 29,
    quantity: '100g',
    description: 'Classic salted potato chips',
  },
  {
    id: '1',
    name: 'Chips',
    image: require('./assets/cheez.jpeg'),
    categoryId: '5',
    price: 24,
    quantity: '200g',
    description: 'Classic salted potato chips',
  },
  {
    id: '2',
    name: 'Cookies',
    image: require('./assets/biscuit.jpg'),
    categoryId: '5',
    price: 299,
    quantity: '500g',
    description: 'Satisfy your crunch cravings',
  },
  {
    id: '3',
    name: 'Juices',
    image: require('./assets/thumbsup.jpeg'),
    categoryId: '6',
    price: 201,
    quantity: '700g',
    description: 'Indulge in the ultimate.',
  },
  {
    id: '4',
    name: 'Soda',
    image: require('./assets/bru.jpg'),
    categoryId: '6',
    price: 29,
    quantity: '100g',
    description: 'Classic salted potato chips',
  },
  {
    id: '1',
    name: 'Chips',
    image: require('./assets/cheez.jpeg'),
    categoryId: '7',
    price: 24,
    quantity: '200g',
    description: 'Classic salted potato chips',
  },
  {
    id: '2',
    name: 'Cookies',
    image: require('./assets/biscuit.jpg'),
    categoryId: '7',
    price: 299,
    quantity: '500g',
    description: 'Satisfy your crunch cravings',
  },
  {
    id: '3',
    name: 'Juices',
    image: require('./assets/thumbsup.jpeg'),
    categoryId: '8',
    price: 201,
    quantity: '700g',
    description: 'Indulge in the ultimate.',
  },
  {
    id: '4',
    name: 'Soda',
    image: require('./assets/bru.jpg'),
    categoryId: '9',
    price: 29,
    quantity: '100g',
    description: 'Classic salted potato chips',
  },
  {
    id: '3',
    name: 'Juices',
    image: require('./assets/thumbsup.jpeg'),
    categoryId: '8',
    price: 201,
    quantity: '700g',
    description: 'Indulge in the ultimate.',
  },
  {
    id: '4',
    name: 'Soda',
    image: require('./assets/bru.jpg'),
    categoryId: '10',
    price: 29,
    quantity: '100g',
    description: 'Classic salted potato chips',
  },
  {
    id: '3',
    name: 'Juices',
    image: require('./assets/thumbsup.jpeg'),
    categoryId: '10',
    price: 201,
    quantity: '700g',
    description: 'Indulge in the ultimate.',
  },
  {
    id: '4',
    name: 'Soda',
    image: require('./assets/bru.jpg'),
    categoryId: '11',
    price: 29,
    quantity: '100g',
    description: 'Classic salted potato chips',
  },
  {
    id: '3',
    name: 'Juices',
    image: require('./assets/thumbsup.jpeg'),
    categoryId: '11',
    price: 201,
    quantity: '700g',
    description: 'Indulge in the ultimate.',
  },
  {
    id: '4',
    name: 'Soda',
    image: require('./assets/bru.jpg'),
    categoryId: '12',
    price: 29,
    quantity: '100g',
    description: 'Classic salted potato chips',
  },
  {
    id: '3',
    name: 'Juices',
    image: require('./assets/thumbsup.jpeg'),
    categoryId: '12',
    price: 201,
    quantity: '700g',
    description: 'Indulge in the ultimate.',
  },
  {
    id: '4',
    name: 'Soda',
    image: require('./assets/bru.jpg'),
    categoryId: '13',
    price: 29,
    quantity: '100g',
    description: 'Classic salted potato chips',
  },
];

export const products = [
  {
    id: '1111',
    name: 'Snickers',
    image: require('./assets/snickers.jpg'),
    price: 24,
    quantity: '200g',
  },
  {
    id: '2111',
    name: 'Oreo',
    image: require('./assets/oreo.jpg'),
    price: 24,
    quantity: '200g',
  },
  {
    id: '3111',
    name: 'Coca-Cola',
    image: require('./assets/cocaloca.jpeg'),
    price: 24,
    quantity: '200g',
  },
  {
    id: '4111',
    name: 'Pepsi',
    image: require('./assets/thumbsup.jpeg'),
    price: 24,
    quantity: '200g',
  },
  {
    id: '5111',
    name: 'KitKat',
    image: require('./assets/kitkat.jpg'),
    price: 24,
    quantity: '200g',
  },
  {
    id: '6111',
    name: 'Noodles',
    image: require('./assets/maggi.jpg'),
    price: 24,
    quantity: '200g',
  },
  {
    id: '7111',
    name: 'Breakfast & sauces',
    image: require('./assets/corn.jpg'),
  },
  {
    id: '8111',
    name: 'Dairy, Bread & Eggs',
    image: require('./assets/amul.jpg'),
  },
];